import { NextResponse } from 'next/server';
import { DemandZone } from '@/types/farmer';

export async function GET() {
  const demandZones: DemandZone[] = [
    {
      id: 'dz-mum',
      region: 'Mumbai — Vashi Wholesale APMC',
      state: 'Maharashtra',
      commodity: 'Tomato (Hybrid Desi)',
      lat: 19.076,
      lng: 72.8777,
      demandKg: 85000,
      supplyKg: 51000,
      gapKg: 34000,
      opportunityLevel: 'High',
      pricePerKg: 52.5,
      buyerCount: 28,
    },
    {
      id: 'dz-hyd',
      region: 'Hyderabad — Shamshabad Terminal',
      state: 'Telangana',
      commodity: 'Red Onion (Nashik)',
      lat: 17.385,
      lng: 78.4867,
      demandKg: 62000,
      supplyKg: 44000,
      gapKg: 18000,
      opportunityLevel: 'High',
      pricePerKg: 38.0,
      buyerCount: 19,
    },
    {
      id: 'dz-blr',
      region: 'Bangalore — Yeshwanthpur Hub',
      state: 'Karnataka',
      commodity: 'Green Chilli (G-4)',
      lat: 12.9716,
      lng: 77.5946,
      demandKg: 35000,
      supplyKg: 31000,
      gapKg: 4000,
      opportunityLevel: 'Medium',
      pricePerKg: 65.0,
      buyerCount: 14,
    },
    {
      id: 'dz-del',
      region: 'Delhi NCR — Azadpur Mandi',
      state: 'Delhi',
      commodity: 'Pukraj Seed Potato',
      lat: 28.7041,
      lng: 77.1025,
      demandKg: 120000,
      supplyKg: 88000,
      gapKg: 32000,
      opportunityLevel: 'High',
      pricePerKg: 24.5,
      buyerCount: 36,
    },
    {
      id: 'dz-che',
      region: 'Chennai — Koyambedu Market',
      state: 'Tamil Nadu',
      commodity: 'Cavendish Banana',
      lat: 13.0827,
      lng: 80.2707,
      demandKg: 48000,
      supplyKg: 46000,
      gapKg: 2000,
      opportunityLevel: 'Moderate',
      pricePerKg: 26.0,
      buyerCount: 11,
    },
    {
      id: 'dz-pun',
      region: 'Pune — Gultekdi APMC',
      state: 'Maharashtra',
      commodity: 'Spinach & Leafy Greens',
      lat: 18.5204,
      lng: 73.8567,
      demandKg: 22000,
      supplyKg: 14000,
      gapKg: 8000,
      opportunityLevel: 'High',
      pricePerKg: 32.0,
      buyerCount: 16,
    },
  ];

  return NextResponse.json(demandZones);
}
