import { ProductDetails, ConsumerOrder, BulkDemand, Recommendation } from "@/types/consumer";

export const mockConsumerProducts: ProductDetails[] = [
  {
    id: "prod-tom-01",
    name: "Farm Fresh Hybrid Tomatoes (Grade A)",
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80",
    grade: "A",
    gradeDescription: "Uniform size, deep red hue, firm texture, ideal for high-end retail and export.",
    availableQuantityKg: 4500,
    minOrderQuantityKg: 50,
    harvestDate: "2026-09-06",
    freshness: "Harvested Today",
    freshnessScore: "Excellent",
    location: "Shadnagar Cluster, Telangana",
    pricePerKg: 38,
    bulkAvailable: true,
    bulkTiers: [
      { minKg: 50, maxKg: 200, pricePerKg: 38, savingsPercent: 0 },
      { minKg: 201, maxKg: 1000, pricePerKg: 34, savingsPercent: 10.5 },
      { minKg: 1001, maxKg: null, pricePerKg: 31, savingsPercent: 18.4 },
    ],
    farmerStory: {
      id: "fst-01",
      farmerName: "Ramesh Reddy & Group",
      farmOrFpoName: "Shadnagar Farmers Collective FPO",
      farmerPhoto: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=300&q=80",
      generalLocation: "Shadnagar Cluster",
      district: "Rangareddy",
      state: "Telangana",
      mainCrops: ["Tomato", "Chilli", "Capsicum"],
      harvestDate: "2026-09-06",
      soilPractices: "Drip fertigation with bio-mulch covering",
      organicPractices: "Neem cake integrated pest management",
      story: "Smallholder cluster spanning 42 acres supplying pesticide-residue tested produce directly to city hubs without commission agents.",
      totalAcresGrown: "42 Acres",
      fairPriceCommitment: "Direct realization: 78% of gross sale value goes directly to farmer bank accounts.",
    },
    priceBreakdown: {
      consumerPricePerKg: 38,
      farmerReceivesPerKg: 29.5,
      roadLogisticsPerKg: 4.5,
      platformFeePerKg: 4.0,
      conventionalMarketPricePerKg: 48,
      farmerRealizationBoostPercent: 28,
    },
    description: "Premium sun-ripened tomatoes carefully hand-picked at 85% color break stage to ensure maximum transit resilience and post-harvest shelf life.",
    isColdChainEligible: true,
    tags: ["Direct Farmer", "Grade A", "Low Chemical Residue"],
    shelfLifeDays: 8,
    optimalStorageTempCelsius: 6,
    nutritionHighlights: ["Vitamin C: 28mg", "Lycopene: 4.2mg", "Dietary Fiber: 1.4g"],
    harvestBatchNumber: "BATCH-SHAD-2026-0906-A",
    qualityInspectionReport: {
      colorScore: 94,
      firmnessScore: 92,
      defectPercentage: 1.2,
      inspectionDate: "2026-09-06",
      inspectorName: "Telangana HortiBoard Certified AI Gateway",
    },
  },
  {
    id: "prod-chl-02",
    name: "Guntur Hot Green Chillies (Grade A)",
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80",
    grade: "A",
    gradeDescription: "Dark green, consistent 8-10cm length, pungent aroma with high capsaicin content.",
    availableQuantityKg: 2200,
    minOrderQuantityKg: 25,
    harvestDate: "2026-09-05",
    freshness: "Harvested 1 Day Ago",
    freshnessScore: "Excellent",
    location: "Tenali Belt, Guntur, Andhra Pradesh",
    pricePerKg: 54,
    bulkAvailable: true,
    bulkTiers: [
      { minKg: 25, maxKg: 100, pricePerKg: 54, savingsPercent: 0 },
      { minKg: 101, maxKg: 500, pricePerKg: 49, savingsPercent: 9.2 },
      { minKg: 501, maxKg: null, pricePerKg: 45, savingsPercent: 16.6 },
    ],
    farmerStory: {
      id: "fst-02",
      farmerName: "K. Venkata Rao",
      farmOrFpoName: "Krishna River Farmers Producer Co.",
      farmerPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
      generalLocation: "Tenali Belt",
      district: "Guntur",
      state: "Andhra Pradesh",
      mainCrops: ["Green Chilli", "Turmeric", "Paddy"],
      harvestDate: "2026-09-05",
      soilPractices: "Alluvial river basin soil with vermicompost",
      organicPractices: "Pheromone traps and trichoderma enrichments",
      story: "Third-generation spice farmers delivering directly into institutional procurement chains.",
      totalAcresGrown: "28 Acres",
      fairPriceCommitment: "Guaranteed minimum support floor + 22% quality bonus for zero-bruising harvest.",
    },
    priceBreakdown: {
      consumerPricePerKg: 54,
      farmerReceivesPerKg: 43.0,
      roadLogisticsPerKg: 5.5,
      platformFeePerKg: 5.5,
      conventionalMarketPricePerKg: 68,
      farmerRealizationBoostPercent: 31,
    },
    description: "Export-grade G4 green chillies harvested in early morning hours to preserve turgidity and snap.",
    isColdChainEligible: true,
    tags: ["High Pungency", "Grade A", "Spices"],
    shelfLifeDays: 12,
    optimalStorageTempCelsius: 8,
    nutritionHighlights: ["Capsaicin: High", "Vitamin A: 140 IU", "Zero Artificial Polish"],
    harvestBatchNumber: "BATCH-GNT-2026-0905-G4",
    qualityInspectionReport: {
      colorScore: 96,
      firmnessScore: 95,
      defectPercentage: 0.8,
      inspectionDate: "2026-09-05",
      inspectorName: "Spices Board APMC Certified",
    },
  },
  {
    id: "prod-oni-03",
    name: "Nashik Premium Red Onions (Grade B)",
    category: "Vegetables",
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80",
    grade: "B",
    gradeDescription: "Well-cured bulbs (45-55mm diameter), triple skin layer, suitable for bulk catering and processing.",
    availableQuantityKg: 8500,
    minOrderQuantityKg: 100,
    harvestDate: "2026-09-03",
    freshness: "Harvested 3 Days Ago",
    freshnessScore: "High",
    location: "Medak Rural, Telangana",
    pricePerKg: 26,
    bulkAvailable: true,
    bulkTiers: [
      { minKg: 100, maxKg: 500, pricePerKg: 26, savingsPercent: 0 },
      { minKg: 501, maxKg: 2000, pricePerKg: 23, savingsPercent: 11.5 },
      { minKg: 2001, maxKg: null, pricePerKg: 20, savingsPercent: 23.0 },
    ],
    farmerStory: {
      id: "fst-03",
      farmerName: "Anjaiah & Medak FPO",
      farmOrFpoName: "Telangana Krishi Vikas FPO",
      farmerPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
      generalLocation: "Medak Rural",
      district: "Medak",
      state: "Telangana",
      mainCrops: ["Onion", "Potato", "Maize"],
      harvestDate: "2026-09-03",
      soilPractices: "Organic compost enriched clay loam",
      organicPractices: "Solar light traps and bio-fungicides",
      story: "A cooperative of 64 marginal farmers pooling storage capacity to avoid distress sales at local mandis.",
      totalAcresGrown: "85 Acres",
      fairPriceCommitment: "Collective cold storage backed transparent warehouse receipts.",
    },
    priceBreakdown: {
      consumerPricePerKg: 26,
      farmerReceivesPerKg: 19.5,
      roadLogisticsPerKg: 3.5,
      platformFeePerKg: 3.0,
      conventionalMarketPricePerKg: 34,
      farmerRealizationBoostPercent: 24,
    },
    description: "Cured red onions stored in ventilated crates. Moisture tested <14% to guarantee minimum sprouting during storage.",
    isColdChainEligible: false,
    tags: ["Bulk Kitchen", "Well Cured", "Grade B"],
    shelfLifeDays: 28,
    optimalStorageTempCelsius: 18,
    nutritionHighlights: ["Quercetin: 45mg", "Moisture: 13.2%", "Zero Sprouting"],
    harvestBatchNumber: "BATCH-MDK-2026-0903-B",
    qualityInspectionReport: {
      colorScore: 88,
      firmnessScore: 86,
      defectPercentage: 3.8,
      inspectionDate: "2026-09-03",
      inspectorName: "FPO Internal Quality Bureau",
    },
  },
  {
    id: "prod-man-04",
    name: "Naturally Ripened Mangoes (Organic Certified)",
    category: "Fruits",
    image: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80",
    grade: "Organic Certified",
    gradeDescription: "Zero carbide chemical ripening, certified organic orchard harvested, heavenly fragrance.",
    availableQuantityKg: 1800,
    minOrderQuantityKg: 20,
    harvestDate: "2026-09-06",
    freshness: "Harvested Today",
    freshnessScore: "Excellent",
    location: "Jadcherla Valley, Mahabubnagar, Telangana",
    pricePerKg: 115,
    bulkAvailable: true,
    bulkTiers: [
      { minKg: 20, maxKg: 100, pricePerKg: 115, savingsPercent: 0 },
      { minKg: 101, maxKg: 500, pricePerKg: 102, savingsPercent: 11.3 },
      { minKg: 501, maxKg: null, pricePerKg: 94, savingsPercent: 18.2 },
    ],
    farmerStory: {
      id: "fst-04",
      farmerName: "Saraswathi Devi",
      farmOrFpoName: "Vana Samrakshana Organic Growers",
      farmerPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80",
      generalLocation: "Jadcherla Valley",
      district: "Mahabubnagar",
      state: "Telangana",
      mainCrops: ["Mango", "Guava", "Custard Apple"],
      harvestDate: "2026-09-06",
      soilPractices: "Zero-budget natural farming with Jeevamrutha",
      organicPractices: "NPOP India Certified Organic #OR-74921",
      story: "Woman-led cooperative managing 18 acres of heritage dryland fruit orchards with solar pumping.",
      totalAcresGrown: "18 Acres",
      fairPriceCommitment: "100% direct realization without middlemen cut.",
    },
    priceBreakdown: {
      consumerPricePerKg: 115,
      farmerReceivesPerKg: 92.0,
      roadLogisticsPerKg: 11.5,
      platformFeePerKg: 11.5,
      conventionalMarketPricePerKg: 155,
      farmerRealizationBoostPercent: 42,
    },
    description: "Orchard fresh naturally tree-ripened organic mangoes cushioned in sugarcane bagasse trays for zero transit bruising.",
    isColdChainEligible: true,
    tags: ["NPOP Certified Organic", "Zero Carbide", "Export Grade"],
    shelfLifeDays: 6,
    optimalStorageTempCelsius: 10,
    nutritionHighlights: ["Brix Index: 18.5°", "Vitamin A & C Rich", "No Pesticide Residue"],
    harvestBatchNumber: "BATCH-MBN-2026-0906-ORG",
    qualityInspectionReport: {
      colorScore: 98,
      firmnessScore: 94,
      defectPercentage: 0.5,
      inspectionDate: "2026-09-06",
      inspectorName: "Organic Certifying Agency India",
    },
  }
];

export const mockConsumerOrders: ConsumerOrder[] = [
  {
    id: "ORD-CONS-801",
    items: [
      {
        product: mockConsumerProducts[0],
        quantityKg: 500,
        selectedTierPricePerKg: 34,
      }
    ],
    totalQuantityKg: 500,
    subtotal: 17000,
    roadLogisticsFee: 850,
    platformFee: 420,
    totalAmount: 18270,
    deliveryAddress: {
      name: "Rajesh Varma",
      phone: "+91 98480 11223",
      address: "Bowenpally Central Wholesale Yard",
      city: "Hyderabad",
      district: "Hyderabad",
      state: "Telangana",
      pincode: "500011",
    },
    paymentMethod: "UPI",
    orderDate: "2026-09-06 11:20 AM",
    status: "In Transit",
    logisticsId: "TRK-CONS-ROAD-9021",
    estimatedDeliveryDate: "Today, 05:45 PM",
  }
];

export const mockBulkDemands: BulkDemand[] = [
  {
    id: "BD-902",
    buyerId: "buyer-001",
    produceName: "Tomato (Grade A)",
    requiredQuantityKg: 5000,
    requiredGrade: "A",
    deliveryLocation: "Bowenpally Wholesale Terminal",
    deliveryCity: "Hyderabad",
    preferredDeliveryDate: "2026-09-08",
    deliveryWindow: "Morning 06:00 - 09:00 AM",
    maxBudgetPerKg: 36,
    matchedQuantityKg: 3800,
    remainingQuantityKg: 1200,
    matchedSuppliers: [
      {
        farmerOrFpoId: "fpo-01",
        name: "Shadnagar Farmers Collective",
        location: "Shadnagar",
        quantityKg: 2400,
        grade: "A",
        contributionPercent: 48,
      }
    ],
    status: "Consolidating",
    roadRouteDetails: {
      traditionalDistanceKm: 210,
      traditionalCost: 4800,
      traditionalHours: 14,
      optimizedDistanceKm: 142,
      optimizedCost: 3100,
      optimizedHours: 8,
      distanceSavedKm: 68,
      costSavedINR: 1700,
      hoursSaved: 6,
    },
    createdAt: "2026-09-06",
  }
];

export const mockRecommendations: Recommendation[] = [
  {
    id: "REC-01",
    produceName: "Tomato (Hybrid)",
    productId: "prod-tom-01",
    headline: "Direct Farm Gate Price Sourcing Advantage",
    explanation: "Combine 3 Shadnagar tomato harvests into single Reefer 407 dispatch to save 18% freight cost.",
    grade: "A",
    freshness: "Harvested Today",
    pricePerKg: 38,
    farmerName: "Ramesh Reddy & Group",
    distanceKm: 42,
    matchingScorePercent: 94,
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=400&q=80",
    suitableBuyerTypes: ["retailer", "bulk-buyer", "restaurant"],
  }
];
